### ISSUE TITLE
standard way to access Postgres error codes

### ISSUE THREAD

**Issue by andreimatei** [jackc/pgconn#15]
Hey there! I'd like to discuss ways to access the error code inside Postgres errors in a way that's compatible across pg drivers (`pgconn/pgx` and `lib/pq`) or, better yet, across any drivers compatible with Go's `sql` package. I figured this is as good of a place to discuss it as any.
cc @mjibson as a `lib/pq` maintainer and @kardianos as a Go `sql` contributor.

Here's the rub: CockroachDB offers this tiny [cockroach-go library](https://github.com/cockroachdb/cockroach-go) which contains some transaction helpers specific to CockroachDB. CockroachDB is wire-compatible with Postgres. cockroach-go tries to support both `lib/pq` and `pgx` (now `pgconn`), and so it has some unfortunate code that looks inside errors to check their error code, looking for a CRDB-specific retriable one:
https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go#L141-L152

Since there's seemingly no common way to get to these code, our library depends on both `lib/pq` and `pgx` and checks the concrete types of errors against `pq.Error` and `pgx.PgError` and then uses the `Code` fields in these structs (which fields, luckily, were public).
Recently, `pgx` published a new version which changed the name of the error struct - it went from `pgx.PgError` to `*pgconn.PgError`. This broke our little library. I could upgrade it to depend on the new version of `pgx` (and accept that not all versions of cockroach-go work with all versions of pgx), but I'd like a better solution.
I'd like `cockroach-go` to not have to depend on either `pgx` or `lib/pq`. I'd like a common interface for these errors that I can test for - simply a `PgCode() string` method.
@jackc and @mjibson - would you mind adding such an interface to the respective errors?

Or, @kardianos, any hope for the `sql` package itself to help in my quest?

Thanks!

**Comment by mjibson** [comment]
This sounds like a good idea. I'm happy to do whatever we need in lib/pq to make a common interface. I recommend we perhaps use the new Go 1.13 new errors stuff so we can use [`errors.Is`](https://golang.org/pkg/errors/#Is), and also use module stuff. That should take care of any version problems? That is, packages like cockroach-go will stop breaking if they use modules.

**Comment by jackc** [comment]
I'd be happy to collaborate on this as well.

>  I could upgrade it to depend on the new version of pgx (and accept that not all versions of cockroach-go work with all versions of pgx)

FWIW however, in this particular case there is an alternative resolution. As far as Go is concerned `github.com/jackc/pgx` and `github.com/jackc/pgx/v4` are separate packages. They can both be used at the same time. Of course, that requires using modules. But if you don't want to move to modules yet it still is solvable. `github.com/jackc/pgx` will continue to import the pre-modules `v3` version. And `github.com/jackc/pgconn` will import the new underlying error struct. Since `pgconn` is still at `v1` it can be imported by pre-module code.

Again, I'm still happy to add a compatible interface with `lib/pq` or support something standardized by `database/sql` -- just wanted to point out it shouldn't be necessary to fix the existing issue.

**Comment by andreimatei** [comment]
Sounds like all the Postgres capos are on board with standardizing access to the error codes in principle, so let's talk specifics. How about
```
interface {
PgCode() string
}
```
There'd be no "standardized" name for this interface; people like me who want to use it would have to type it out themselves (analogous to the interface for wrapper errors in the go 1.13 ). Sounds good?

------------------
Separately, I'd love to be schooled on modules and how I could use them to have `cockroach-go` work with both pgx v3 and v4, if you have time, Jack. I'm not really familiar with modules; the CockroachDB codebase does not use them yet (we're big on vendoring, though).
So, if `cockroach-go` doesn't use modules, importing `github.com/jackc/pgx` gives us `v4`, not `v3`. I think this is in contradiction to what Jack is saying... But I believe it's a fact :)
Now, if `cockroach-go` would use modules, then what? You're saying it could import both `github.com/jackc/pgx/v4` and `github.com/jackc/pgx` (or perhaps `github.com/jackc/pgx/v3`?), and then it'd have access to both `pgx.PgError` and `pgconn.PgError`. Cool! But what I'm not sure about is how this affects users of `cockroach-go` that don't themselves use modules (i.e., if I understand correctly, users that keep `GO111MODULE` to the default of `auto`). For these users, would the import of  `github.com/jackc/pgx/v3` still work?
Another thing that I'm unsure about is how using modules would interact with vendoring. If a user of `cockroch-go` has vendored `pgx` and `cockroach-go` started using modules, would either of ``github.com/jackc/pgx/v4` or `github.com/jackc/pgx` refer to the vendored version? Because if they don't, I think we have a problem. The way in which `cockroach-go` depends on `pgx` is a bit unusual: `cockroach-go` takes a closure from the client, and that client might be using (its version of) `pgx`. And `cockroach-go` needs to process an error coming out of this closure and see if it's a pgx error. So, for example, `cockroach-go` cannot vendor `pgx` because then, due to how vendoring works, we'd be unable to recognize an error coming from the client's pgx... If that makes sense.

**Comment by jackc** [comment]
Would it make sense to use the name `SQLState` instead of `PgCode`? That is the SQL standard that PostgreSQL uses (https://en.wikipedia.org/wiki/SQLSTATE and https://www.postgresql.org/docs/current/errcodes-appendix.html). This name would let the same interface be used by non-PostgreSQL databases and might make it more useful for `database/sql` in general.

---

As far as modules go, if you're not using Go modules importing `github.com/jackc/pgx` will get you the latest version before there is a `go.mod` file with a version greater than 1. I believe that behavior was ported all the way back to Go 1.9.

You would never import `github.com/jackc/pgx/v3` -- that predated modules -- you would just import `github.com/jackc/pgx` to get the latest non-module version.

Here is an example that doesn't use modules and uses `github.com/jackc/pgx` and `github.com/jackc/pgconn`.

```go
package main

import (
	"context"
	"log"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgx" // should be v3
)

func main() {
	usePgxV3()
	usePgConn()
}

func usePgxV3() {
	c, err := pgx.ParseEnvLibpq() // this method only exists in v3 / the pre-modules pgx
	if err != nil {
		log.Fatal(err)
	}

	db, err := pgx.NewConnPool(pgx.ConnPoolConfig{ConnConfig: c})
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	var n int
	err = db.QueryRow("select 42").Scan(&n)
	if err != nil {
		log.Fatal(err)

	}

	if n != 42 {
		log.Fatalln("didn't get expected num")
	}

	log.Println("pgx v3 succeeded")
}

func usePgConn() {
	db, err := pgconn.Connect(context.Background(), "")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close(context.Background())

	results := db.ExecParams(context.Background(), "select 42", nil, nil, nil, nil).Read()
	if results.Err != nil {
		log.Fatal(results.Err)
	}

	if string(results.Rows[0][0]) != "42" {
		log.Fatalln("didn't get expected num")
	}

	log.Println("pgconn succeeded")
}
```

```
jack@glados ~/go/src/github.com/jackc/test-pgx-without-modules » PGHOST=/private/tmp go run main.go                                                              1 ↵
2019/09/16 14:42:53 pgx v3 succeeded
2019/09/16 14:42:53 pgconn succeeded
```

**Comment by mjibson** [comment]
I'm fine with `SQLState() string`. I feel like `Message() string` and `Detail() string` would also be useful. Those three fields cover most of my use cases. But I'm ok with whatever.

**Comment by jackc** [comment]
`Message() string` and `Detail() string` wouldn't work for `pgconn` because they are already public fields on the `PgError` struct. https://godoc.org/github.com/jackc/pgconn#PgError

**Comment by jackc** [comment]
I added the `SQLState() string` method to pgconn.PgError. I also back ported it to pgx v3.

**Comment by andreimatei** [comment]
Thank you!

**Comment by awmcclain** [comment]
I'm really sorry if this isn't the correct place to ask this -- but I'm missing the connection of how to actually use `SQLState()` in code.

Say I'm using an ORM that uses pgex under the hood. I check my err using `errors.As()` in order to match the sql state:
``` 
// See if we have a serialization failure
var pge *pgconn.PgError
if errors.As(err, &pge) {
	if pge.SQLState() == "40001" || pge.SQLState() == "40P01" {
              // Handle serialization failure
	}
}
```

However, if my ORM switches out pgex for a different postgres driver, wouldn't that `errors.As` check fail?

Again, apologies if this is a naive question -- my go knowledge is patchy.

**Comment by jackc** [comment]
> However, if my ORM switches out pgex for a different postgres driver, wouldn't that errors.As check fail?

Yes. Unfortunately, there is no standard way to get SQLSTATE in the Go standard library.
