### ISSUE TITLE
Do not include default fallback when parsing empty string

### ISSUE THREAD

**Issue by kingluo** [jackc/pgconn#42]
As a library, I think it's most likely to use `ConnectConfig` instead of `Connect` with url string. But `ConnectConfig` would check if it's parsed, so it need to call `pgconn.ParseConfig("")` first, which would include `localhost:5432` as default fallback. It's seriously wrong IMO, because it would use wrong connection if the main connection failed to establish.
So, I'm wondering what's the original consideration? Could you please fix it?

**Comment by jackc** [comment]
The default behavior was designed to match the standard C library `libpq`.

**Comment by kingluo** [comment]
> The default behavior was designed to match the standard C library `libpq`.

However, it would cause implicit, werid and wrong behavior. For example, in my case, I specify the target server host and port (other than 5432), meanwhile, the 5432 port also has one postgres instance running, then when my target server goes down and I start my program, pgx would connect to 5432 without any error reporting and make it look likes everything is ok while it doesn't!

So far,  I just set Fallback to nil as workaround.

**Comment by jackc** [comment]
I think I understand what you mean now. The issue is the `FallbackConfig` that is created automatically to handle the default `sslmode` of `prefer`, not that `5432` is the default port if none is specified.

I agree now that this is undesirable behavior, but I'm still considering what the solution should be.

Not including the `FallbackConfig` for an empty string would be a breaking change. Someone could be using the `PGHOST` environment variable. If their server did not support SSL this change would break their connection.

We could allow creating a `Config` directly, but that would break `PG*` environment variable support, `.pgpass` support, and more. Also there are a lot of settings that are required and that `ParseConfig` sets up. One of the original reasons for requiring the use of `ParseConfig` is that building an entire `Config` from scratch is difficult and allowing it complicates adding new settings that need default values.

Another option is for this auto-generated fallback for `sslmode` to be special cased somehow where it will use the `Host` and `Port` of the top level config instead of its own fields.

But as I look more it seems there are is at least one more case where the combination of parsing a connection string and then changing the `Host` would cause a failure. This could also occur if `PGSSLMODE=verify-full` because the `tls.Config` would try to verify the wrong host.

So the fundamental issue is it can be unsafe to change `Host` and `Port` after a `Config` is created because other configuration is derived from them.

What I'm leaning toward now is adding either `NewConfig(host string, port uint16)` or `NewConfig(settings map[string]interface{})`. I'd also document that `Host` and `Port` should not be changed after construction of the `Config`.

**Comment by jackc** [comment]
An alternative to `NewConfig(settings map[string]interface{})` would be a function that converts a `map[string]interface{}` to a connection string.

**Comment by kingluo** [comment]
I think `ConnectConfig()` is necessary, so `NewConfig()` seems good. Please add such function.

**Comment by jackc** [comment]
I've found an additional foot-gun with the default `sslmode` of `prefer`. If someone used `ParseConfig()` or the proposed `NewConfig()` and then set a custom `tls.Config` the `Fallback` without TLS from the `sslmode` would still be there. This could lead to a connection that unexpectedly lacked encryption.

All of these different issues are related to fallbacks. Fallbacks are only used for insecure SSL modes and for specifying multiple hosts for high availability connections. The simplest fix might be to allow disabling them. Something like:

```go
config, err := pgconn.ParseConfig("", pgconn.DisableFallbacks)
```

This could be done without adding a new public function or changing the signature of `ParseConfig()` in an incompatible way.

**Comment by jackc** [comment]
I had difficulty figuring out how to explain in documentation the purpose of the above suggested `pgconn.DisableFallbacks`. So I went back to `NewConfig()`. `NewConfig()` now creates a `Config` with the connection settings empty.

**Comment by kingluo** [comment]
Maybe it's better to add default ssl config in `NewConfig()` just like `ParseConfig("")`?

**Comment by jackc** [comment]
SSL cannot be configured without the host. That's why I initially was thinking that `NewConfig()` would take host as an argument. But that still leaves the problem that changing `Host` on the `Config` struct will not change the `tls.Config` or any fallbacks.

Fundamentally, the issue is the `Config` struct represents a "resolved" or "flattened" config. All the interdependent settings like `Host`, `TLSConfig`, and `Fallbacks` are resolved from the connection string and environment.

In hindsight, perhaps I should have originally made the `Config` struct read only. Maybe the better way forward would be to document the strong recommendation _not_ to mutate the `Config` except in specifically allowed ways. It's pretty easy to build a conn string from other structured data. e.g.

```go
ParseConfig(fmt.Sprintf("host=%s database=%s", settings["host"], settings["database"])
```

And maybe add a conn string builder helper like `MapToConnString`. 

No tagged releases have been made yet, so it is still safe to revert or change `NewConfig()`.

**Comment by jackc** [comment]
I decided to revert `NewConfig()` in favor of additional documentation recommending against changing a returned Config, but also explaining how to safely do so.

`NewConfig` had the problems of lacking default SSL as you mentioned, lacking all the other libpq defaults, and it also would need a parallel `NewConfig` in `pgx` and in `pgxpool`.

I'm open to reconsidering this at some point, but I'd like to see if the improved documentation is sufficient.
