### ISSUE TITLE
Add BeforeConnect

### ISSUE THREAD

**Issue by dankinder** [jackc/pgconn#71]
I would be willing to implement this but want to make sure it would be desired. I propose the addition of a `BeforeConnect` hook, like `AfterConnect` that would be called [here](https://github.com/jackc/pgconn/blob/464a7d88d9ccf1ca9f76a84984d95a5657ac3faa/pgconn.go#L129)

I have a similar motivation to https://github.com/jackc/pgx/issues/819 -- in my case, I'm using cockroachDB and would love to be able to rotate the host order on each connection and not bother with haproxy. I would implement a simple version of BeforeConnect that alters the Host and Fallbacks to randomly reorder the hosts. We could include it in this repository as well if desired, like `ValidateConnectTargetSessionAttrsReadWrite`.

I could also imagine this being useful for users that want to distribute load across standbys, or want to use the hostname to prioritize connecting to a location closer to where the app is running, things like that.

**Comment by jackc** [comment]
This sounds similar to https://github.com/jackc/pgx/pull/901 and https://github.com/jackc/pgx/issues/676. If you are using pgxpool with the `BeforeConnect` hook there should do what you want.

If your not using pgxpool then it might be more difficult. To be honest, a generalized `BeforeConnect` hook that can arbitrarily modify / create a connection config feels like the wrong abstraction for pgconn. Each `ConnectConfig` / `*PgConn` is a entirely independent. It doesn't make sense to pass it a config object which contains instructions to modify itself. IMO, modifying a config only makes sense in the context of multiple connections using the same config. i.e. at the connection pool level.

That said, I recognize that if you are using the  `database/sql` interface instead of `pgxpool` that might be difficult or impossible.  So I might be open to violating my design sensibilities if it's the only way... But perhaps if it is a `database/sql` issue maybe this functionality belongs in `pgx/stdlib` instead of here.

**Comment by dankinder** [comment]
Ah I didn't even think to see if pgxpool had this, since i'm using `pgx/stdlib`. I'll investigate switching us to pgxpool first instead.

Either way I would need to write a `func RandomizeHostOrderFunc(ctx context.Context, cfg *pgx.ConnConfig) error` -- would you want that to be a helper in pgxpool?

**Comment by dankinder** [comment]
Actually I remembered why using native pgx/pgxpool was not easy: I'm using sqlx. Comments from [this issue](https://github.com/jackc/pgx/issues/647) indicate that trying to use both so that I can use `BeforeConnect` will be pretty challenging. That does make the original proposal pretty tempting...

**Comment by jackc** [comment]
I looked at this a little more and I think that the right location for this would be in `pgx/stdlib`. There already is a `AfterConnect` implementation usable with `OpenDB` (https://pkg.go.dev/github.com/jackc/pgx/v4@v4.11.0/stdlib#OptionOpenDB). I think this would be the correct location for a `BeforeConnect` hook with `database/sql`.
